version: '3.9'

services:
  app:
    container_name: auth-service
    build: .
    command: ./app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      auth-db:
        condition: service_healthy

  auth-db:
    restart: no
    image: postgres:16
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
